import { defineConfig, globalIgnores } from 'eslint/config';
import reactHooksPlugin from 'eslint-plugin-react-hooks';
import reactPlugin from 'eslint-plugin-react';
import tseslint from 'typescript-eslint';

export default defineConfig([
  globalIgnores([
    '**/node_modules/**',
    '**/dist/**',
    '**/build/**',
    '**/.react-router/**',
    '**/.well-known/**',
    '**/paraglide/**',
    // Generated by `wrangler types`; linting it only reports directives emitted
    // by Wrangler itself and makes the repository gate depend on generated code.
    '**/worker-configuration.d.ts',
  ]),
  // @ts-expect-error
  tseslint.configs.recommended,
  //
  reactPlugin.configs.flat.recommended,
  reactPlugin.configs.flat['jsx-runtime'],
  reactHooksPlugin.configs['recommended-latest'],
  {
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          ignoreRestSiblings: true,
          varsIgnorePattern: '^_',
        },
      ],
      // Keep legacy boundary casts visible without making the repository-wide
      // gate unusable; newly touched code should still avoid adding warnings.
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-empty-object-type': 'warn',
      // Runtime prop-types duplicate TypeScript's component contracts.
      'react/prop-types': 'off',
      // Apostrophes and quotation marks in JSX text are safe and substantially
      // clearer in authored product/legal copy than entity escapes.
      'react/no-unescaped-entities': 'off',
      // Frontière front→serveur (issue #25 / V2.4) : apps/mail ne doit plus tirer les
      // sources serveur via un chemin relatif ; les contrats partagés passent par
      // @zero/types. Le pattern `**/server/src/**` ne matche PAS les sous-chemins
      // publics `@zero/server/*` (auth/schemas/trpc), qui restent autorisés.
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/server/src/**'],
              message:
                'Frontière front→serveur : importez les contrats partagés depuis @zero/types, pas les sources @zero/server via un chemin relatif (issue #25).',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['**/*.test.ts', '**/*.test.tsx'],
    rules: {
      // Test doubles intentionally cross typed SDK/runtime boundaries. Keep the
      // production rules strict while allowing concise, local harness adapters.
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-unsafe-function-type': 'off',
      // Test helpers can intentionally call hooks under renderHook wrappers
      // without themselves being React components.
      'react-hooks/rules-of-hooks': 'off',
    },
  },
  {
    files: ['**/*.d.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      'no-var': 'off',
    },
  },
  {
    files: ['**/lib/react-emails/**/*.tsx'],
    rules: {
      // Email copy is text content, not executable HTML; escaping apostrophes
      // makes the authored templates substantially less readable.
      'react/no-unescaped-entities': 'off',
    },
  },
]);
